### ISSUE TITLE
I need to compile the source code. instructions?

### ISSUE THREAD

**Issue by PSSGAMER** [Sovamorco/BHBot#21]
Title. Im having issues cause win7 and compiling with fix it. 
Thanks.

**Comment by Sovamorco** [comment]
1. Install python3.10 and all the necessary libraries (I don't have a full list so just install stuff until `python gui.py` runs without errors)
2. From root of the repository run `pyinstaller --onedir --windowed --icon icon.ico --name BHBot --add-data icon.ico;. --add-data languages;languages/ --add-data fonts;fonts/ --add-data modes/default;modes/default/ --add-data modes/examples;modes/examples/ gui.py`
3. Compiled bot should be in dist folder

**Comment by Sovamorco** [comment]
I don't actually know requirements for running the bot so try to run `pip install fontTools keyboard mouse PySimpleGUI PyUpdater pywin32 requests Pillow psutil` and it will probably be enough. After you run this command try running `python gui.py` in repository root and see if the bot starts. If it does then you can compile it with step 2 of my previous comment.
And BTW forgot to mention but bot might not work on windows 7 at all because I have not tested it and also it is heavily nerfed now so it might not work regardless of the system because BMG noticed afk farming ig. I should probably update readme with all that.

**Comment by PSSGAMER** [comment]
https://imgur.com/wQPpKIJ
Maybe u can help me with error.

**Comment by PSSGAMER** [comment]
Failed to execute script gui unhandled exception. No module named regex

Traceback (most recent call last):
  File "gui.py", line 3, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "bot.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "windows.py", line 8, in <module>
ModuleNotFoundError: No module named 'regex'

**Comment by Sovamorco** [comment]
Missed one it seems, just do pip install regex

**Comment by PSSGAMER** [comment]
Works although stuck at game window resizing. Runs on loop.

**Comment by PSSGAMER** [comment]
Traceback (most recent call last):
  File "gui.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "bot.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "config.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "abstract_mode.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "utils.py", line 310, in <module>
  File "utils.py", line 158, in load
  File "utils.py", line 128, in __init__
  File "pyupdater\client\__init__.py", line 245, in update_check
  File "pyupdater\client\__init__.py", line 337, in _update_check
  File "pyupdater\client\updates.py", line 744, in __init__
  File "pyupdater\client\updates.py", line 470, in __init__
AssertionError

**Comment by Sovamorco** [comment]
Well, I don't really know and can't really advise on issues with Windows 7 so you'll have to go on a marvelous adventure of trying to find what's wrong.
Or not, probably not worth it
