### ISSUE TITLE
ive got this error, keeps crashing was wondering if u knew what this meant as i dont know a single thing about coding thanks

### ISSUE THREAD

**Issue by skylerkhoo** [Sovamorco/BHBot#24]
Exception in thread Thread-17 (main_loop):
Traceback (most recent call last):
  File "threading.py", line 1009, in _bootstrap_inner
  File "threading.py", line 946, in run
  File "bot.py", line 350, in main_loop
  File "bot.py", line 324, in main_sequence
  File "bot.py", line 357, in get_states
  File "windows.py", line 176, in make_screenshot
win32ui.error: DeleteDC failed

**Comment by AbyssalKaz** [comment]
I happened to get the same issue just now, although it happened while I had my monitor screen off so I didn't see it in action.

If your wondering I'm on Windows 10 Version 21H2 Build (19044.1889)

**Comment by Sovamorco** [comment]
Well, I thought about it for a bit, and it can happen because of a bunch of unrelated things, so just turn on autostart and it should work. Bot will just restart itself like 5 minutes after crashing

**Comment by AbyssalKaz** [comment]
Didn't see that as a thing, I'll try it!
![image](https://user-images.githubusercontent.com/113244522/189486000-d42be504-6cc0-43b6-a8f3-b2333c5530c9.png)
