### ISSUE TITLE
bot stuck

### ISSUE THREAD

**Issue by ramonQAQ** [Sovamorco/BHBot#28]
![image](https://user-images.githubusercontent.com/96535082/218537047-f7239237-4f4a-4cd8-96fa-be691833c677.png
the bot seem to can't go into stealth mode

**Comment by Sovamorco** [comment]
Put game into windowed mode
  

  

  

  
  
  
  
  
>

**Comment by ramonQAQ** [comment]
> 

it gives me this error 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 954, in _bootstrap_inner
  File "threading.py", line 892, in run
  File "bot.py", line 263, in main_loop
  File "bot.py", line 228, in main_sequence
  File "bot.py", line 96, in initialize
  File "bot.py", line 92, in ensure_brawlhalla
  File "windows.py", line 151, in hide
  File "windows.py", line 138, in move_off_screen
pywintypes.error: (5, 'SetWindowPos', 'Access is denied.')

**Comment by Sovamorco** [comment]
Probably Steam or the game was ran as admin and the bot as user.
  

  

  

  
  
  
  
  
>

**Comment by ramonQAQ** [comment]
yes that seemed to fix it ty for your help <3
