### ISSUE TITLE
new issue :(

### ISSUE THREAD

**Issue by ramonQAQ** [Sovamorco/BHBot#29]
Error recognizing level
Bot only works with levels 1-100
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 954, in _bootstrap_inner
  File "threading.py", line 892, in run
  File "bot.py", line 263, in main_loop
  File "bot.py", line 228, in main_sequence
  File "bot.py", line 108, in initialize
  File "bot.py", line 356, in get_characters
  File "levels.py", line 86, in get_level
levels.LevelNotDetected

**Comment by Nick2bad4u** [comment]
same

**Comment by Sovamorco** [comment]
Should be fixed in 3.5.12

**Comment by Nick2bad4u** [comment]
> Should be fixed in 3.5.12

Any idea on release date?

**Comment by Nick2bad4u** [comment]
This has been fixed and can be accessed via his [Website](https://sovamor.co/bhbot).

He gave me this info in Discord.

@ramonQAQ 

@Sovamorco Thanks again!
